---
layout: default
---

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>STAT207 Final Project - Clutch Completion In Penguins</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  { }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="Final_Project_files/libs/clipboard/clipboard.min.js"></script>
<script src="Final_Project_files/libs/quarto-html/quarto.js"></script>
<script src="Final_Project_files/libs/quarto-html/popper.min.js"></script>
<script src="Final_Project_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Final_Project_files/libs/quarto-html/anchor.min.js"></script>
<link href="Final_Project_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Final_Project_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Final_Project_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Final_Project_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Final_Project_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">STAT207 Final Project - Clutch Completion In Penguins</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>Contribution Report:</strong></p>
<p>Sammy Haskel - Section 1, 3, 5,</p>
<p>Isabella Iniguez - Section 3, 4, 7</p>
<p>Ava Zheng - Section 2, 7, Presentation</p>
<p>Syed Ammar Raza - Section 6, 8, 9</p>
<div id="cell-2" class="cell" data-execution_count="178">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Imports here</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> confusion_matrix</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> roc_curve</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> roc_auc_score</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> cross_val_score</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> KFold</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegression</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.exceptions <span class="im">import</span> ConvergenceWarning</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>warnings.simplefilter(action<span class="op">=</span><span class="st">'ignore'</span>, category<span class="op">=</span><span class="pp">FutureWarning</span>)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>warnings.simplefilter(action<span class="op">=</span><span class="st">'ignore'</span>, category<span class="op">=</span>ConvergenceWarning)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>, message<span class="op">=</span><span class="st">"Maximum Likelihood optimization failed to"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">1. Introduction</h2>
<section id="primary-research-goal" class="level3">
<h3 class="anchored" data-anchor-id="primary-research-goal">Primary Research Goal</h3>
<p>Build a predictive model that will effectively predict Clutch Completion for new datasets.</p>
</section>
<section id="secondary-research-goal" class="level3">
<h3 class="anchored" data-anchor-id="secondary-research-goal">Secondary Research Goal</h3>
<ul>
<li><p>Ideally, the predictive model that we select will be able to yield reliable interpretive insights of the nature of the relationship between our explanatory variables and between our explanatory variables and Clutch Completion.</p></li>
<li><p>Ideally, the predictive model that we select will also be able to accurately reflect and describe the relationship between the explanatory variables and the response variable clutch competition.</p></li>
</ul>
</section>
<section id="research-motivation" class="level3">
<h3 class="anchored" data-anchor-id="research-motivation">Research Motivation</h3>
<p>The motivation for why someone might want to build a predictive model that predicts Clutch Completion could be to assess whether or not features like flipper length and body mass play a role in a penguin completing clutch (Gorman, Kristen B et al.). An animal biologist/conservationist may find our model useful to assist with research or help with conservation of the penguins. (Davis, Lloyd S et al.). This person would likely desire a classifier that shows a high accuracy of positives (higher true positive rate) with a low rate of negatives (low false positive rate). This is because penguins who have completed clutch (had a nest with 2 eggs) are more likely to have one chick survive (United Parks &amp; Resorts, n.d.-b). So if this person is actively working on conserving these species of penguins, by having a high true positive rate with a low false positive rate, they can have a better minimum guess for the number of chicks born.</p>
<p>CITATIONS:</p>
<ul>
<li><p>Davis, Lloyd S et al.&nbsp;“The breeding biology of erect-crested penguins, Eudyptes sclateri: Hormones, behavior, obligate brood reduction and conservation.” PloS one vol.&nbsp;17,10 e0275106. 12 Oct.&nbsp;2022, doi:10.1371/journal.pone.0275106</p></li>
<li><p>Gorman, Kristen B et al.&nbsp;“Ecological sexual dimorphism and environmental variability within a community of antarctic penguins (Genus Pygoscelis).” PloS one vol.&nbsp;9,3 e90081. 5 Mar.&nbsp;2014, doi:10.1371/journal.pone.0090081</p></li>
<li><p>Penguins Reproduction. United Parks &amp; Resorts. (n.d.-b). https://seaworld.org/animals/all-about/penguins/reproduction/</p></li>
</ul>
</section>
</section>
<section id="dataset-discussion" class="level2">
<h2 class="anchored" data-anchor-id="dataset-discussion">2. Dataset Discussion</h2>
<p><strong>Source</strong></p>
<p>We got the dataset from Kaggle. It was downloaded from the following link: https://www.kaggle.com/datasets/parulpandey/palmer-archipelago-antarctica-penguin-data. It was downloaded on April 17th, 2024.</p>
<p><strong>Original Dataset Information</strong></p>
<p>The each row in the dataset represents one penguin and tells us information on the species, where it’s from, which study it is apart of, gender, measurements, and clutch completion. Kaggle does not state how the data was collected, but there is links that include more information on how the studies were conducted.</p>
<p>This dataset includes a large number of all the possible types, but one observation that could of been included could be estimated age of the penguins. Based on that estimated age is not included, the researcher would make conclusion based on a more generalized population of penguins and not based on estimated ages of penguins.</p>
<p><strong>Selected Variables</strong> The variable we are choosing to be our response variable is clutch completion.</p>
<p>The explanatory variables are Species, Island, Body Mass (g), Flipper Length (mm), and Sex. We chose to use these variables because they consist of data that is collected and unique to each penguin.</p>
<div id="cell-7" class="cell" data-outputid="26cc7a7a-ed61-4ee9-a148-42537571e7d8" data-execution_count="93">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df<span class="op">=</span>pd.read_csv(<span class="st">'penguins_lter.csv'</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>df.head(<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="93">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">studyName</th>
<th data-quarto-table-cell-role="th">Sample Number</th>
<th data-quarto-table-cell-role="th">Species</th>
<th data-quarto-table-cell-role="th">Region</th>
<th data-quarto-table-cell-role="th">Island</th>
<th data-quarto-table-cell-role="th">Stage</th>
<th data-quarto-table-cell-role="th">Individual ID</th>
<th data-quarto-table-cell-role="th">Clutch Completion</th>
<th data-quarto-table-cell-role="th">Date Egg</th>
<th data-quarto-table-cell-role="th">Culmen Length (mm)</th>
<th data-quarto-table-cell-role="th">Culmen Depth (mm)</th>
<th data-quarto-table-cell-role="th">Flipper Length (mm)</th>
<th data-quarto-table-cell-role="th">Body Mass (g)</th>
<th data-quarto-table-cell-role="th">Sex</th>
<th data-quarto-table-cell-role="th">Delta 15 N (o/oo)</th>
<th data-quarto-table-cell-role="th">Delta 13 C (o/oo)</th>
<th data-quarto-table-cell-role="th">Comments</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>PAL0708</td>
<td>1</td>
<td>Adelie Penguin (Pygoscelis adeliae)</td>
<td>Anvers</td>
<td>Torgersen</td>
<td>Adult, 1 Egg Stage</td>
<td>N1A1</td>
<td>Yes</td>
<td>11/11/07</td>
<td>39.1</td>
<td>18.7</td>
<td>181.0</td>
<td>3750.0</td>
<td>MALE</td>
<td>NaN</td>
<td>NaN</td>
<td>Not enough blood for isotopes.</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>PAL0708</td>
<td>2</td>
<td>Adelie Penguin (Pygoscelis adeliae)</td>
<td>Anvers</td>
<td>Torgersen</td>
<td>Adult, 1 Egg Stage</td>
<td>N1A2</td>
<td>Yes</td>
<td>11/11/07</td>
<td>39.5</td>
<td>17.4</td>
<td>186.0</td>
<td>3800.0</td>
<td>FEMALE</td>
<td>8.94956</td>
<td>-24.69454</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>PAL0708</td>
<td>3</td>
<td>Adelie Penguin (Pygoscelis adeliae)</td>
<td>Anvers</td>
<td>Torgersen</td>
<td>Adult, 1 Egg Stage</td>
<td>N2A1</td>
<td>Yes</td>
<td>11/16/07</td>
<td>40.3</td>
<td>18.0</td>
<td>195.0</td>
<td>3250.0</td>
<td>FEMALE</td>
<td>8.36821</td>
<td>-25.33302</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>PAL0708</td>
<td>4</td>
<td>Adelie Penguin (Pygoscelis adeliae)</td>
<td>Anvers</td>
<td>Torgersen</td>
<td>Adult, 1 Egg Stage</td>
<td>N2A2</td>
<td>Yes</td>
<td>11/16/07</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>Adult not sampled.</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>PAL0708</td>
<td>5</td>
<td>Adelie Penguin (Pygoscelis adeliae)</td>
<td>Anvers</td>
<td>Torgersen</td>
<td>Adult, 1 Egg Stage</td>
<td>N3A1</td>
<td>Yes</td>
<td>11/16/07</td>
<td>36.7</td>
<td>19.3</td>
<td>193.0</td>
<td>3450.0</td>
<td>FEMALE</td>
<td>8.76651</td>
<td>-25.32426</td>
<td>NaN</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-8" class="cell" data-outputid="4f3021b1-57a9-4bcd-de30-2015c4e744b0" data-execution_count="94">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Length of original dataframe:"</span>, <span class="bu">len</span>(df))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Length of original dataframe: 344</code></pre>
</div>
</div>
</section>
<section id="dataset-cleaning" class="level2">
<h2 class="anchored" data-anchor-id="dataset-cleaning">3. Dataset Cleaning</h2>
<p>First, we’ll create a new dataframe with only the relevant variable columns we’ll be exploring.</p>
<div id="cell-11" class="cell" data-outputid="3ec44d28-202f-4e72-9cf6-70aa3ddf39b0" data-execution_count="95">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>df_vars <span class="op">=</span> df[[<span class="st">'Clutch Completion'</span>,<span class="st">'Species'</span>,<span class="st">'Island'</span>,<span class="st">'Body Mass (g)'</span>,<span class="st">'Flipper Length (mm)'</span>,<span class="st">'Sex'</span>]]</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>df_vars.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="95">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Clutch Completion</th>
<th data-quarto-table-cell-role="th">Species</th>
<th data-quarto-table-cell-role="th">Island</th>
<th data-quarto-table-cell-role="th">Body Mass (g)</th>
<th data-quarto-table-cell-role="th">Flipper Length (mm)</th>
<th data-quarto-table-cell-role="th">Sex</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Yes</td>
<td>Adelie Penguin (Pygoscelis adeliae)</td>
<td>Torgersen</td>
<td>3750.0</td>
<td>181.0</td>
<td>MALE</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Yes</td>
<td>Adelie Penguin (Pygoscelis adeliae)</td>
<td>Torgersen</td>
<td>3800.0</td>
<td>186.0</td>
<td>FEMALE</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Yes</td>
<td>Adelie Penguin (Pygoscelis adeliae)</td>
<td>Torgersen</td>
<td>3250.0</td>
<td>195.0</td>
<td>FEMALE</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Yes</td>
<td>Adelie Penguin (Pygoscelis adeliae)</td>
<td>Torgersen</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Yes</td>
<td>Adelie Penguin (Pygoscelis adeliae)</td>
<td>Torgersen</td>
<td>3450.0</td>
<td>193.0</td>
<td>FEMALE</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-12" class="cell" data-outputid="45cd6a81-7a9f-455e-bc5a-65432771a198" data-execution_count="96">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>df_vars.isna().<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="96">
<pre><code>Clutch Completion       0
Species                 0
Island                  0
Body Mass (g)           2
Flipper Length (mm)     2
Sex                    10
dtype: int64</code></pre>
</div>
</div>
<div id="cell-13" class="cell" data-outputid="75a8e2e5-50d9-4b94-82f1-652b2b0a7793" data-execution_count="97">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>df_dropna <span class="op">=</span> df_vars.dropna()</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="bu">len</span>(df) <span class="op">-</span> <span class="bu">len</span>(df_dropna)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="97">
<pre><code>10</code></pre>
</div>
</div>
<p><strong>Missing Value Detection and Cleaning</strong></p>
<p>Our dataset did have some implicit mising values. Looking at all the unique values of Sex, there were some penguins who had a period in place of a gender. To deal with the missing value, we decided to drop the row with the missing values.</p>
<p>The pro of using this method as it removes the missing information. The con is that we are losing information, but as we are only dropping one row out of 334 it is relatively negligible.</p>
<div id="cell-15" class="cell" data-outputid="782b741b-0721-4d7b-80e3-a28f46a4a7b5" data-execution_count="98">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>df_dropna[<span class="st">'Clutch Completion'</span>].unique()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="98">
<pre><code>array(['Yes', 'No'], dtype=object)</code></pre>
</div>
</div>
<div id="cell-16" class="cell" data-outputid="095d6ad3-699a-4ecf-d752-7db3cc0d3885" data-execution_count="99">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>df_dropna[<span class="st">'Sex'</span>].unique()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="99">
<pre><code>array(['MALE', 'FEMALE', '.'], dtype=object)</code></pre>
</div>
</div>
<div id="cell-17" class="cell" data-outputid="9af7f9f9-84ac-4f46-84fa-5751224758c9" data-execution_count="100">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>df_dropna[<span class="st">'Island'</span>].unique()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="100">
<pre><code>array(['Torgersen', 'Biscoe', 'Dream'], dtype=object)</code></pre>
</div>
</div>
<div id="cell-18" class="cell" data-outputid="f3a864e1-3aaa-4961-f99a-00efbc374d59" data-execution_count="101">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>df_dropna[<span class="st">'Species'</span>].unique()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="101">
<pre><code>array(['Adelie Penguin (Pygoscelis adeliae)',
       'Chinstrap penguin (Pygoscelis antarctica)',
       'Gentoo penguin (Pygoscelis papua)'], dtype=object)</code></pre>
</div>
</div>
<div id="cell-19" class="cell" data-outputid="6b823356-53db-447f-fc79-a77b87248d7f" data-execution_count="102">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>df_dropna[<span class="st">'Body Mass (g)'</span>].unique()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="102">
<pre><code>array([3750., 3800., 3250., 3450., 3650., 3625., 4675., 3200., 4400.,
       3700., 4500., 3325., 4200., 3400., 3600., 3950., 3550., 3150.,
       3900., 3300., 4150., 4650., 3100., 3000., 4600., 3425., 3500.,
       4300., 4050., 2900., 2850., 3350., 4100., 3050., 4450., 4250.,
       4000., 4700., 4350., 3725., 4725., 3075., 2925., 3175., 4775.,
       3825., 4275., 4075., 3775., 3875., 3275., 4475., 3975., 3475.,
       3525., 3575., 4550., 3850., 4800., 2700., 3675., 5700., 5400.,
       5200., 5150., 5550., 5850., 6300., 5350., 5000., 5050., 5100.,
       5650., 5250., 6050., 4950., 4750., 4900., 5300., 4850., 5800.,
       6000., 5950., 4625., 5450., 5600., 4875., 4925., 4975., 5500.,
       4575., 4375., 5750.])</code></pre>
</div>
</div>
<div id="cell-20" class="cell" data-outputid="3717713b-9b46-4e57-e178-020564bb9c2d" data-execution_count="103">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>df_dropna[<span class="st">'Flipper Length (mm)'</span>].unique()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="103">
<pre><code>array([181., 186., 195., 193., 190., 182., 191., 198., 185., 197., 184.,
       194., 174., 180., 189., 187., 183., 172., 178., 188., 196., 200.,
       192., 202., 205., 208., 203., 199., 176., 210., 201., 212., 206.,
       207., 211., 230., 218., 215., 219., 209., 214., 216., 213., 217.,
       221., 222., 220., 225., 224., 231., 229., 223., 228., 226.])</code></pre>
</div>
</div>
<div id="cell-21" class="cell" data-outputid="2e9724c7-cb51-49f5-ec64-292da367e2ff" data-execution_count="104">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>df_cleaned <span class="op">=</span> df_dropna[df_dropna[<span class="st">'Sex'</span>] <span class="op">!=</span> <span class="st">'.'</span>].reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="bu">len</span>(df_dropna) <span class="op">-</span> <span class="bu">len</span>(df_cleaned)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="104">
<pre><code>1</code></pre>
</div>
</div>
<div id="cell-22" class="cell" data-outputid="2a9c8726-4857-49ce-cf39-3f3f289d409a" data-execution_count="105">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Number of rows after cleaning:"</span>, <span class="bu">len</span>(df_cleaned))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of rows after cleaning: 333</code></pre>
</div>
</div>
<p>All categorical explanatory variables have suffiecently large observations per category (at least 10)</p>
<div id="cell-24" class="cell" data-outputid="36eb1d23-129d-4390-8eed-ce0ca6f42113" data-execution_count="106">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>df_cleaned.groupby(<span class="st">'Species'</span>).agg(<span class="st">'count'</span>).reset_index()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="106">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Species</th>
<th data-quarto-table-cell-role="th">Clutch Completion</th>
<th data-quarto-table-cell-role="th">Island</th>
<th data-quarto-table-cell-role="th">Body Mass (g)</th>
<th data-quarto-table-cell-role="th">Flipper Length (mm)</th>
<th data-quarto-table-cell-role="th">Sex</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Adelie Penguin (Pygoscelis adeliae)</td>
<td>146</td>
<td>146</td>
<td>146</td>
<td>146</td>
<td>146</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Chinstrap penguin (Pygoscelis antarctica)</td>
<td>68</td>
<td>68</td>
<td>68</td>
<td>68</td>
<td>68</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Gentoo penguin (Pygoscelis papua)</td>
<td>119</td>
<td>119</td>
<td>119</td>
<td>119</td>
<td>119</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-25" class="cell" data-outputid="6a19c39a-803b-4053-9e96-151f74ebdad3" data-execution_count="107">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>df_cleaned.groupby(<span class="st">'Island'</span>).agg(<span class="st">'count'</span>).reset_index()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="107">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Island</th>
<th data-quarto-table-cell-role="th">Clutch Completion</th>
<th data-quarto-table-cell-role="th">Species</th>
<th data-quarto-table-cell-role="th">Body Mass (g)</th>
<th data-quarto-table-cell-role="th">Flipper Length (mm)</th>
<th data-quarto-table-cell-role="th">Sex</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Biscoe</td>
<td>163</td>
<td>163</td>
<td>163</td>
<td>163</td>
<td>163</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Dream</td>
<td>123</td>
<td>123</td>
<td>123</td>
<td>123</td>
<td>123</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Torgersen</td>
<td>47</td>
<td>47</td>
<td>47</td>
<td>47</td>
<td>47</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-26" class="cell" data-outputid="dbf2f890-fc26-4e28-e846-21d0b9778ce5" data-execution_count="108">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>df_cleaned.groupby(<span class="st">'Sex'</span>).agg(<span class="st">'count'</span>).reset_index()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="108">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Sex</th>
<th data-quarto-table-cell-role="th">Clutch Completion</th>
<th data-quarto-table-cell-role="th">Species</th>
<th data-quarto-table-cell-role="th">Island</th>
<th data-quarto-table-cell-role="th">Body Mass (g)</th>
<th data-quarto-table-cell-role="th">Flipper Length (mm)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>FEMALE</td>
<td>165</td>
<td>165</td>
<td>165</td>
<td>165</td>
<td>165</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>MALE</td>
<td>168</td>
<td>168</td>
<td>168</td>
<td>168</td>
<td>168</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><strong>Outlier Cleaning - Two Variable Outlier Inspection</strong></p>
<p>We only have one pair of numerical explanatory variables, and we see that there arent any significant nor obvious outliers, so we make the decision to no drop any rows. There isn’t a risk of certain points skewing the model.</p>
<div id="cell-28" class="cell" data-outputid="0f5dca2c-73f3-4ff1-c812-59964cf276ef" data-execution_count="109">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(x<span class="op">=</span>df_cleaned[<span class="st">'Body Mass (g)'</span>],y<span class="op">=</span>df_cleaned[<span class="st">'Flipper Length (mm)'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/cell-19-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Other Data Cleaning</strong></p>
<p>When we tried to answer our research questions, we did not discover any other data cleaning ideas that might help make the answer to the research question more clear. Thus, we choose to not perfrom any additional data cleaning.</p>
<p>After all cleaning, we are left with a dataset with 333 rows and 6 columns. We dropped a total of 11 rows.</p>
<div id="cell-31" class="cell" data-outputid="4abc1883-7c09-45ed-b35d-2d031504455e" data-execution_count="110">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>df_cleaned</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="110">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Clutch Completion</th>
<th data-quarto-table-cell-role="th">Species</th>
<th data-quarto-table-cell-role="th">Island</th>
<th data-quarto-table-cell-role="th">Body Mass (g)</th>
<th data-quarto-table-cell-role="th">Flipper Length (mm)</th>
<th data-quarto-table-cell-role="th">Sex</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Yes</td>
<td>Adelie Penguin (Pygoscelis adeliae)</td>
<td>Torgersen</td>
<td>3750.0</td>
<td>181.0</td>
<td>MALE</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Yes</td>
<td>Adelie Penguin (Pygoscelis adeliae)</td>
<td>Torgersen</td>
<td>3800.0</td>
<td>186.0</td>
<td>FEMALE</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Yes</td>
<td>Adelie Penguin (Pygoscelis adeliae)</td>
<td>Torgersen</td>
<td>3250.0</td>
<td>195.0</td>
<td>FEMALE</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Yes</td>
<td>Adelie Penguin (Pygoscelis adeliae)</td>
<td>Torgersen</td>
<td>3450.0</td>
<td>193.0</td>
<td>FEMALE</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Yes</td>
<td>Adelie Penguin (Pygoscelis adeliae)</td>
<td>Torgersen</td>
<td>3650.0</td>
<td>190.0</td>
<td>MALE</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">328</td>
<td>No</td>
<td>Gentoo penguin (Pygoscelis papua)</td>
<td>Biscoe</td>
<td>4925.0</td>
<td>214.0</td>
<td>FEMALE</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">329</td>
<td>Yes</td>
<td>Gentoo penguin (Pygoscelis papua)</td>
<td>Biscoe</td>
<td>4850.0</td>
<td>215.0</td>
<td>FEMALE</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">330</td>
<td>Yes</td>
<td>Gentoo penguin (Pygoscelis papua)</td>
<td>Biscoe</td>
<td>5750.0</td>
<td>222.0</td>
<td>MALE</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">331</td>
<td>Yes</td>
<td>Gentoo penguin (Pygoscelis papua)</td>
<td>Biscoe</td>
<td>5200.0</td>
<td>212.0</td>
<td>FEMALE</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">332</td>
<td>Yes</td>
<td>Gentoo penguin (Pygoscelis papua)</td>
<td>Biscoe</td>
<td>5400.0</td>
<td>213.0</td>
<td>MALE</td>
</tr>
</tbody>
</table>

<p>333 rows × 6 columns</p>
</div>
</div>
</div>
</section>
<section id="preliminary-analysis" class="level2">
<h2 class="anchored" data-anchor-id="preliminary-analysis">4. Preliminary Analysis</h2>
<p><strong>Relationships between the Response Variable and the Explanatory Variables</strong></p>
<p><code>Species</code> has somewhat of a strong relationship with <code>Clutch Completion</code>, because there is a difference between the Clutch Completion rates (the two bars) depending on the Species of penguin.</p>
<div id="cell-35" class="cell" data-outputid="8e153d83-caee-41a6-bf8c-c09564918b39" data-execution_count="111">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>temp <span class="op">=</span> pd.crosstab(df_cleaned[<span class="st">'Species'</span>], df_cleaned[<span class="st">'Clutch Completion'</span>], normalize<span class="op">=</span><span class="st">'index'</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>temp.plot.bar(rot<span class="op">=</span><span class="dv">25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/cell-21-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><code>Island</code> has somewhat of a strong relationship with <code>Clutch Completion</code>, because there is a difference between the Clutch Completion rates (the two bars) depending on the Island the penguins reside in.</p>
<div id="cell-37" class="cell" data-outputid="95440318-00f1-4837-88bf-a12b6aefee6e" data-execution_count="112">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>temp <span class="op">=</span> pd.crosstab(df_cleaned[<span class="st">'Island'</span>], df_cleaned[<span class="st">'Clutch Completion'</span>], normalize<span class="op">=</span><span class="st">'index'</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>temp.plot.bar()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/cell-22-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><code>Sex</code> has a weak relationship with <code>Clutch Completion</code>, because there is no apparent difference between the Clutch Completion rates (the two bars) depending on the Island the penguins reside in.</p>
<div id="cell-39" class="cell" data-outputid="a93b436f-a03f-4f30-928d-ab3470c961f5" data-execution_count="113">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>temp <span class="op">=</span> pd.crosstab(df_cleaned[<span class="st">'Sex'</span>], df_cleaned[<span class="st">'Clutch Completion'</span>], normalize<span class="op">=</span><span class="st">'index'</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>temp.plot.bar()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/cell-23-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><code>Body Mass (g)</code> has a somewhat strong relationship with <code>Clutch Completion</code>, because there is a lot of overlap in the IQR of Body Mass depending on the Clutch Completion state.</p>
<div id="cell-41" class="cell" data-outputid="73a671ba-a9b1-45c3-e127-03cb0410aacc" data-execution_count="114">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>sns.boxplot(x<span class="op">=</span><span class="st">'Clutch Completion'</span>, y<span class="op">=</span><span class="st">'Body Mass (g)'</span>, data<span class="op">=</span>df_cleaned)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/cell-24-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><code>Flipper Length (mm)</code> has a somewhat strong relationship with <code>Clutch Completion</code>, because there is a difference in the IQR of Flipper Lengths depending on the Clutch Completion state.</p>
<div id="cell-43" class="cell" data-outputid="de563390-5d23-49da-c4a3-b6cdc760b410" data-execution_count="115">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>sns.boxplot(x<span class="op">=</span><span class="st">'Clutch Completion'</span>, y<span class="op">=</span><span class="st">'Flipper Length (mm)'</span>, data<span class="op">=</span>df_cleaned)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/cell-25-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Relationships between Explanatory Variable Pairs</strong></p>
<p><code>Species</code> has a very strong association with <code>Island</code>, because there is a large difference in the distribution of species of penguin depending on the Island.</p>
<div id="cell-46" class="cell" data-outputid="62e36262-4aaa-4c2c-e0ac-2276e4805561" data-execution_count="116">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>temp <span class="op">=</span> pd.crosstab(df_cleaned[<span class="st">'Island'</span>], df_cleaned[<span class="st">'Species'</span>], normalize<span class="op">=</span><span class="st">'index'</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>temp.plot.bar()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/cell-26-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><code>Sex</code> has a weak association with <code>Island</code>, because there is minor difference in the distribution of sex depending on the Island.</p>
<div id="cell-48" class="cell" data-outputid="ca8c77b7-c8a1-4e9e-df48-301922da6d8b" data-execution_count="117">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>temp <span class="op">=</span> pd.crosstab(df_cleaned[<span class="st">'Island'</span>], df_cleaned[<span class="st">'Sex'</span>], normalize<span class="op">=</span><span class="st">'index'</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>temp.plot.bar()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/cell-27-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><code>Body Mass (g)</code> has a strong association with <code>Island</code>, because there is a large difference in the Body Mass IQRs between Islands.</p>
<div id="cell-50" class="cell" data-outputid="76b003db-4177-43a6-f74f-35581ad1af27" data-execution_count="118">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>sns.boxplot(x<span class="op">=</span><span class="st">'Island'</span>, y<span class="op">=</span><span class="st">'Body Mass (g)'</span>, data<span class="op">=</span>df_cleaned)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/cell-28-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><code>Flipper Length (mm)</code> has a strong association with <code>Island</code>, because there is a large difference in the Flipper Length IQRs between Islands.</p>
<div id="cell-52" class="cell" data-outputid="9f508ed2-e2cc-4102-a5d0-ac573ab797ea" data-execution_count="119">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>sns.boxplot(x<span class="op">=</span><span class="st">'Island'</span>, y<span class="op">=</span><span class="st">'Flipper Length (mm)'</span>, data<span class="op">=</span>df_cleaned)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/cell-29-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><code>Species</code> has a very weak association with <code>Sex</code>, because there is relatively no difference in the distribution of sex depending on the Species.</p>
<div id="cell-54" class="cell" data-outputid="a3fe0186-80b0-4e9f-dae7-4b6c9e28ecda" data-execution_count="120">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>temp <span class="op">=</span> pd.crosstab(df_cleaned[<span class="st">'Species'</span>], df_cleaned[<span class="st">'Sex'</span>], normalize<span class="op">=</span><span class="st">'index'</span>)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>temp.plot.bar()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/cell-30-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><code>Body Mass (g)</code> has a strong association with <code>Species</code>, because there is a large difference in the Body Mass IQRs between Species.</p>
<div id="cell-56" class="cell" data-outputid="5f0906e9-472f-4075-cb63-475d14d1fac2" data-execution_count="121">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>sns.boxplot(x<span class="op">=</span><span class="st">'Species'</span>, y<span class="op">=</span><span class="st">'Body Mass (g)'</span>, data<span class="op">=</span>df_cleaned)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/cell-31-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><code>Flipper Length (mm)</code> has a strong association with <code>Species</code>, because there is a large difference in the Flipper Length IQRs between Species.</p>
<div id="cell-58" class="cell" data-outputid="c3cb265e-077e-47f8-d7d1-e0ae55975be3" data-execution_count="122">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>sns.boxplot(x<span class="op">=</span><span class="st">'Species'</span>, y<span class="op">=</span><span class="st">'Flipper Length (mm)'</span>, data<span class="op">=</span>df_cleaned)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/cell-32-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><code>Flipper Length (mm)</code> has a strong association with <code>Sex</code>, because there is a difference in the Flipper Length IQRs between Sexes.</p>
<div id="cell-60" class="cell" data-outputid="80bae74b-342a-4187-e209-fd3e5a173ba8" data-execution_count="123">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>sns.boxplot(x<span class="op">=</span><span class="st">'Sex'</span>, y<span class="op">=</span><span class="st">'Flipper Length (mm)'</span>, data<span class="op">=</span>df_cleaned)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/cell-33-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><code>Body Mass (g)</code> has a strong association with <code>Sex</code>, because there is a difference in the Flipper Length IQRs between Sexes.</p>
<div id="cell-62" class="cell" data-outputid="4ea914cc-cc6f-442b-d95a-fb9887aa00d1" data-execution_count="124">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>sns.boxplot(x<span class="op">=</span><span class="st">'Sex'</span>, y<span class="op">=</span><span class="st">'Body Mass (g)'</span>, data<span class="op">=</span>df_cleaned)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/cell-34-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><code>Body Mass (g)</code> has a strong association with <code>Flipper Length (mm)</code>, because there is a fairly obvious linear relationship between Body Mass and Flipper Length as per the scatterplot.</p>
<div id="cell-64" class="cell" data-outputid="16bacfb5-cc10-4d59-874e-877bd304c8b0" data-execution_count="125">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(x<span class="op">=</span><span class="st">'Body Mass (g)'</span>, y<span class="op">=</span><span class="st">'Flipper Length (mm)'</span>, data<span class="op">=</span>df_cleaned)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/cell-35-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interaction Effects</strong></p>
<p>First we convert the Yes/No <code>Clutch Completion</code> response variable into a 1/0 <code>y</code> variable.</p>
<div id="cell-66" class="cell" data-execution_count="126">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>df_cleaned[<span class="st">'y'</span>] <span class="op">=</span> pd.get_dummies(df_cleaned[<span class="st">'Clutch Completion'</span>], drop_first<span class="op">=</span><span class="va">True</span>, dtype<span class="op">=</span><span class="bu">int</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We see below that the line of best fit between <code>Body Mass (g)</code> and <code>Clutch Completion</code> changes between the value of <code>Species</code>, thus there is likely a large interaction between the two explanatory variables on Clutch Completion.</p>
<div id="cell-68" class="cell" data-outputid="e0ffa04d-393a-48cd-e768-1e3815f8e5cb" data-execution_count="127">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>sns.lmplot(x<span class="op">=</span><span class="st">'Body Mass (g)'</span>, y<span class="op">=</span><span class="st">'y'</span>, hue<span class="op">=</span><span class="st">'Species'</span>, data<span class="op">=</span>df_cleaned, logistic<span class="op">=</span><span class="va">True</span>, ci<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/cell-37-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>We see below that the line of best fit between <code>Flipper Length (mm)</code> and <code>Clutch Completion</code> changes between the value of <code>Species</code>, thus there is likely a large interaction between the two explanatory variables on Clutch Completion.</p>
<div id="cell-70" class="cell" data-outputid="576be97f-1348-4d8a-eb71-4b61509c47cb" data-execution_count="128">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>sns.lmplot(x<span class="op">=</span><span class="st">'Flipper Length (mm)'</span>, y<span class="op">=</span><span class="st">'y'</span>, hue<span class="op">=</span><span class="st">'Species'</span>, data<span class="op">=</span>df_cleaned, logistic<span class="op">=</span><span class="va">True</span>, ci<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/cell-38-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>We see below that the line of best fit between <code>Body Mass (g)</code> and <code>Clutch Completion</code> changes between the value of <code>Island</code>, thus there is likely a large interaction between the two explanatory variables on Clutch Completion.</p>
<div id="cell-72" class="cell" data-outputid="6a0730f5-0ad8-427e-b356-1fad6fb6100f" data-execution_count="129">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>sns.lmplot(x<span class="op">=</span><span class="st">'Body Mass (g)'</span>, y<span class="op">=</span><span class="st">'y'</span>, hue<span class="op">=</span><span class="st">'Island'</span>, data<span class="op">=</span>df_cleaned, logistic<span class="op">=</span><span class="va">True</span>, ci<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/cell-39-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>We see below that the line of best fit between <code>Flipper Length (mm)</code> and <code>Clutch Completion</code> changes between the value of <code>Island</code>, thus there is likely a large interaction between the two explanatory variables on Clutch Completion.</p>
<div id="cell-74" class="cell" data-outputid="1c785b33-e25c-4e3c-b7ce-4b9385a2f926" data-execution_count="130">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>sns.lmplot(x<span class="op">=</span><span class="st">'Flipper Length (mm)'</span>, y<span class="op">=</span><span class="st">'y'</span>, hue<span class="op">=</span><span class="st">'Island'</span>, data<span class="op">=</span>df_cleaned, logistic<span class="op">=</span><span class="va">True</span>, ci<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/cell-40-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>We see below that the line of best fit between <code>Body Mass (g)</code> and <code>Clutch Completion</code> changes between the value of <code>Sex</code>, thus there is likely a large interaction between the two explanatory variables on Clutch Completion.</p>
<div id="cell-76" class="cell" data-outputid="2e529532-2d63-4164-b89f-2ecb6808c167" data-execution_count="131">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>sns.lmplot(x<span class="op">=</span><span class="st">'Body Mass (g)'</span>, y<span class="op">=</span><span class="st">'y'</span>, hue<span class="op">=</span><span class="st">'Sex'</span>, data<span class="op">=</span>df_cleaned, logistic<span class="op">=</span><span class="va">True</span>, ci<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/cell-41-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>We see below that the line of best fit between <code>Flipper Length (mm)</code> and <code>Clutch Completion</code> doesn’t really differ between the value of <code>Sex</code>, thus there is likely no interaction between the two explanatory variables on Clutch Completion.</p>
<div id="cell-78" class="cell" data-outputid="daca7f1d-4624-4800-ee91-59eb11c7d6b2" data-execution_count="132">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>sns.lmplot(x<span class="op">=</span><span class="st">'Flipper Length (mm)'</span>, y<span class="op">=</span><span class="st">'y'</span>, hue<span class="op">=</span><span class="st">'Sex'</span>, data<span class="op">=</span>df_cleaned, logistic<span class="op">=</span><span class="va">True</span>, ci<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/cell-42-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="model-data-preprocessing" class="level2">
<h2 class="anchored" data-anchor-id="model-data-preprocessing">5. Model Data Preprocessing</h2>
<p><strong>0/1 Response Variable</strong></p>
<p>Has already been created in previous section (<code>y</code>).</p>
<div id="cell-81" class="cell" data-outputid="3c7fce14-7d47-4d5e-a4f5-e19f73debd4c" data-execution_count="133">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>X_df <span class="op">=</span> df_cleaned.drop([<span class="st">'Clutch Completion'</span>], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>X_df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="133">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Species</th>
<th data-quarto-table-cell-role="th">Island</th>
<th data-quarto-table-cell-role="th">Body Mass (g)</th>
<th data-quarto-table-cell-role="th">Flipper Length (mm)</th>
<th data-quarto-table-cell-role="th">Sex</th>
<th data-quarto-table-cell-role="th">y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Adelie Penguin (Pygoscelis adeliae)</td>
<td>Torgersen</td>
<td>3750.0</td>
<td>181.0</td>
<td>MALE</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Adelie Penguin (Pygoscelis adeliae)</td>
<td>Torgersen</td>
<td>3800.0</td>
<td>186.0</td>
<td>FEMALE</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Adelie Penguin (Pygoscelis adeliae)</td>
<td>Torgersen</td>
<td>3250.0</td>
<td>195.0</td>
<td>FEMALE</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Adelie Penguin (Pygoscelis adeliae)</td>
<td>Torgersen</td>
<td>3450.0</td>
<td>193.0</td>
<td>FEMALE</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Adelie Penguin (Pygoscelis adeliae)</td>
<td>Torgersen</td>
<td>3650.0</td>
<td>190.0</td>
<td>MALE</td>
<td>1</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-82" class="cell" data-outputid="d81baa58-b5fa-4081-c897-11e7de7f16f4" data-execution_count="134">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>y_df <span class="op">=</span> df_cleaned[<span class="st">'y'</span>]</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>y_df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="134">
<pre><code>0    1
1    1
2    1
3    1
4    1
Name: y, dtype: int64</code></pre>
</div>
</div>
<div id="cell-83" class="cell" data-execution_count="135">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>numeric_df <span class="op">=</span> df_cleaned[[<span class="st">'Body Mass (g)'</span>, <span class="st">'Flipper Length (mm)'</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-84" class="cell" data-outputid="471d66d2-cc04-4292-84af-5e94e14340eb" data-execution_count="136">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>scaler_df <span class="op">=</span> StandardScaler()</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>scaled_expl_vars <span class="op">=</span> scaler_df.fit_transform(numeric_df)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>X_scaler <span class="op">=</span> pd.DataFrame(scaled_expl_vars, columns<span class="op">=</span>numeric_df.columns)</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>X_scaler.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="136">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Body Mass (g)</th>
<th data-quarto-table-cell-role="th">Flipper Length (mm)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>-0.568475</td>
<td>-1.426752</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>-0.506286</td>
<td>-1.069474</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>-1.190361</td>
<td>-0.426373</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>-0.941606</td>
<td>-0.569284</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>-0.692852</td>
<td>-0.783651</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-85" class="cell" data-execution_count="137">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>cat_df <span class="op">=</span> df_cleaned[[<span class="st">'Species'</span>, <span class="st">'Island'</span>, <span class="st">'Sex'</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-86" class="cell" data-outputid="f9070b0e-0216-48fa-9870-9f7156ae8451" data-execution_count="138">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>indicator_Df <span class="op">=</span> pd.get_dummies(cat_df, drop_first<span class="op">=</span><span class="va">True</span>, dtype<span class="op">=</span><span class="bu">int</span>)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>indicator_Df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="138">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Species_Chinstrap penguin (Pygoscelis antarctica)</th>
<th data-quarto-table-cell-role="th">Species_Gentoo penguin (Pygoscelis papua)</th>
<th data-quarto-table-cell-role="th">Island_Dream</th>
<th data-quarto-table-cell-role="th">Island_Torgersen</th>
<th data-quarto-table-cell-role="th">Sex_MALE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">328</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">329</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">330</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">331</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">332</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
</tbody>
</table>

<p>333 rows × 5 columns</p>
</div>
</div>
</div>
<div id="cell-87" class="cell" data-outputid="da7c6bd6-db8a-46a1-d1c8-ab0c7b614358" data-execution_count="139">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>X_df <span class="op">=</span> pd.concat([X_scaler, indicator_Df], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>X_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="139">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Body Mass (g)</th>
<th data-quarto-table-cell-role="th">Flipper Length (mm)</th>
<th data-quarto-table-cell-role="th">Species_Chinstrap penguin (Pygoscelis antarctica)</th>
<th data-quarto-table-cell-role="th">Species_Gentoo penguin (Pygoscelis papua)</th>
<th data-quarto-table-cell-role="th">Island_Dream</th>
<th data-quarto-table-cell-role="th">Island_Torgersen</th>
<th data-quarto-table-cell-role="th">Sex_MALE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>-0.568475</td>
<td>-1.426752</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>-0.506286</td>
<td>-1.069474</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>-1.190361</td>
<td>-0.426373</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>-0.941606</td>
<td>-0.569284</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>-0.692852</td>
<td>-0.783651</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">328</td>
<td>0.892957</td>
<td>0.931283</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">329</td>
<td>0.799674</td>
<td>1.002739</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">330</td>
<td>1.919069</td>
<td>1.502928</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">331</td>
<td>1.234995</td>
<td>0.788372</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">332</td>
<td>1.483749</td>
<td>0.859828</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
</tbody>
</table>

<p>333 rows × 7 columns</p>
</div>
</div>
</div>
</section>
<section id="feature-selection-with-k-fold-cross-validation" class="level2">
<h2 class="anchored" data-anchor-id="feature-selection-with-k-fold-cross-validation">6. Feature Selection with k-Fold Cross-Validation</h2>
<div id="cell-89" class="cell" data-outputid="c842dd24-9677-49e3-87dc-a708eef4d032" data-execution_count="140">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>cross_val <span class="op">=</span> KFold(n_splits<span class="op">=</span><span class="dv">5</span>, shuffle<span class="op">=</span><span class="va">True</span>, random_state<span class="op">=</span><span class="dv">207</span>)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>cross_val</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="140">
<pre><code>KFold(n_splits=5, random_state=207, shuffle=True)</code></pre>
</div>
</div>
<div id="cell-90" class="cell" data-execution_count="141">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>log_model <span class="op">=</span> LogisticRegression()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-91" class="cell" data-outputid="fd2fc602-0c43-4d80-ae57-e2ac66dc336e" data-execution_count="142">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>test_fold_auc <span class="op">=</span> cross_val_score(log_model, X_df, y_df, cv<span class="op">=</span>cross_val, scoring<span class="op">=</span><span class="st">'roc_auc'</span>)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Test Fold AUC values:'</span>, test_fold_auc)</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Mean Test Fold AUC:'</span>, test_fold_auc.mean())</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Std Test Fold AUC:'</span>, test_fold_auc.std())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Test Fold AUC values: [0.74285714 0.67580645 0.47669492 0.61530172 0.67070218]
Mean Test Fold AUC: 0.636272482607794
Std Test Fold AUC: 0.08945770087016215</code></pre>
</div>
</div>
<section id="backwards-elimination" class="level3">
<h3 class="anchored" data-anchor-id="backwards-elimination">Backwards Elimination</h3>
<div id="cell-93" class="cell" data-outputid="ec741a0c-5f9f-4b93-d39c-f6e5fa68cce5" data-execution_count="143">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>X_without_bodymass <span class="op">=</span> X_df[[<span class="st">'Flipper Length (mm)'</span>, <span class="st">'Species_Chinstrap penguin (Pygoscelis antarctica)'</span>, <span class="st">'Species_Gentoo penguin (Pygoscelis papua)'</span>, <span class="st">'Island_Dream'</span>, <span class="st">'Island_Torgersen'</span>, <span class="st">'Sex_MALE'</span>]]</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>test_fold_auc <span class="op">=</span> cross_val_score(log_model, X_without_bodymass, y_df, cv<span class="op">=</span>cross_val, scoring<span class="op">=</span><span class="st">'roc_auc'</span>)</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Test Fold AUC values:'</span>, test_fold_auc)</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Mean Test Fold AUC:'</span>, test_fold_auc.mean())</span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Std Test Fold AUC:'</span>, test_fold_auc.std())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Test Fold AUC values: [0.72857143 0.66935484 0.58580508 0.60344828 0.69128329]
Mean Test Fold AUC: 0.6556925841734292
Std Test Fold AUC: 0.05362538958406206</code></pre>
</div>
</div>
<div id="cell-94" class="cell" data-outputid="8687ac32-c711-43b8-9962-0949f3f2fd9d" data-execution_count="144">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>X_without_flipper <span class="op">=</span> X_df[[<span class="st">'Body Mass (g)'</span>, <span class="st">'Species_Chinstrap penguin (Pygoscelis antarctica)'</span>, <span class="st">'Species_Gentoo penguin (Pygoscelis papua)'</span>, <span class="st">'Island_Dream'</span>, <span class="st">'Island_Torgersen'</span>, <span class="st">'Sex_MALE'</span>]]</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>test_fold_auc <span class="op">=</span> cross_val_score(log_model, X_without_flipper, y_df, cv<span class="op">=</span>cross_val, scoring<span class="op">=</span><span class="st">'roc_auc'</span>)</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Test Fold AUC values:'</span>, test_fold_auc)</span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Mean Test Fold AUC:'</span>, test_fold_auc.mean())</span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Std Test Fold AUC:'</span>, test_fold_auc.std())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Test Fold AUC values: [0.73333333 0.64677419 0.48940678 0.66918103 0.65375303]
Mean Test Fold AUC: 0.6384896735319757
Std Test Fold AUC: 0.08057864717938311</code></pre>
</div>
</div>
<div id="cell-95" class="cell" data-outputid="de664fcf-f856-4ce2-d02c-6a9ff3cbf5ce" data-execution_count="145">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>X_without_sex <span class="op">=</span> X_df[[<span class="st">'Flipper Length (mm)'</span>, <span class="st">'Body Mass (g)'</span>, <span class="st">'Species_Chinstrap penguin (Pygoscelis antarctica)'</span>, <span class="st">'Species_Gentoo penguin (Pygoscelis papua)'</span>, <span class="st">'Island_Dream'</span>, <span class="st">'Island_Torgersen'</span>]]</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>test_fold_auc <span class="op">=</span> cross_val_score(log_model, X_without_sex, y_df, cv<span class="op">=</span>cross_val, scoring<span class="op">=</span><span class="st">'roc_auc'</span>)</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Test Fold AUC values:'</span>, test_fold_auc)</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Mean Test Fold AUC:'</span>, test_fold_auc.mean())</span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Std Test Fold AUC:'</span>, test_fold_auc.std())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Test Fold AUC values: [0.72619048 0.67258065 0.48516949 0.63685345 0.65375303]
Mean Test Fold AUC: 0.634909417557487
Std Test Fold AUC: 0.08066258037144781</code></pre>
</div>
</div>
<div id="cell-96" class="cell" data-outputid="9e2179f2-41bb-4410-8973-92578a23e972" data-execution_count="146">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>X_without_species <span class="op">=</span> X_df[[<span class="st">'Flipper Length (mm)'</span>, <span class="st">'Body Mass (g)'</span>, <span class="st">'Island_Dream'</span>, <span class="st">'Island_Torgersen'</span>, <span class="st">'Sex_MALE'</span>]]</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>test_fold_auc <span class="op">=</span> cross_val_score(log_model, X_without_species, y_df, cv<span class="op">=</span>cross_val, scoring<span class="op">=</span><span class="st">'roc_auc'</span>)</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Test Fold AUC values:'</span>, test_fold_auc)</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Mean Test Fold AUC:'</span>, test_fold_auc.mean())</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Std Test Fold AUC:'</span>, test_fold_auc.std())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Test Fold AUC values: [0.61190476 0.73387097 0.45974576 0.58081897 0.55447942]
Mean Test Fold AUC: 0.5881639753524004
Std Test Fold AUC: 0.08885267404971228</code></pre>
</div>
</div>
<div id="cell-97" class="cell" data-outputid="236a02e4-125f-4e94-f9ec-60139768e34f" data-execution_count="147">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>X_without_island <span class="op">=</span> X_df[[<span class="st">'Flipper Length (mm)'</span>, <span class="st">'Body Mass (g)'</span>, <span class="st">'Species_Chinstrap penguin (Pygoscelis antarctica)'</span>, <span class="st">'Species_Gentoo penguin (Pygoscelis papua)'</span>, <span class="st">'Sex_MALE'</span>]]</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>test_fold_auc <span class="op">=</span> cross_val_score(log_model, X_without_island, y_df, cv<span class="op">=</span>cross_val, scoring<span class="op">=</span><span class="st">'roc_auc'</span>)</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Test Fold AUC values:'</span>, test_fold_auc)</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Mean Test Fold AUC:'</span>, test_fold_auc.mean())</span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Std Test Fold AUC:'</span>, test_fold_auc.std())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Test Fold AUC values: [0.75238095 0.69516129 0.45974576 0.6174569  0.65133172]
Mean Test Fold AUC: 0.6352153242190901
Std Test Fold AUC: 0.09867722151365058</code></pre>
</div>
</div>
<div id="cell-98" class="cell" data-outputid="4b15feda-5f8b-42cb-e5b3-93f207a8e339" data-execution_count="148">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>X_without_bodymass_flipper <span class="op">=</span> X_df[[<span class="st">'Species_Chinstrap penguin (Pygoscelis antarctica)'</span>, <span class="st">'Species_Gentoo penguin (Pygoscelis papua)'</span>, <span class="st">'Island_Dream'</span>, <span class="st">'Island_Torgersen'</span>, <span class="st">'Sex_MALE'</span>]]</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>test_fold_auc <span class="op">=</span> cross_val_score(log_model, X_without_bodymass_flipper, y_df, cv<span class="op">=</span>cross_val, scoring<span class="op">=</span><span class="st">'roc_auc'</span>)</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Test Fold AUC values:'</span>, test_fold_auc)</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Mean Test Fold AUC:'</span>, test_fold_auc.mean())</span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Std Test Fold AUC:'</span>, test_fold_auc.std())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Test Fold AUC values: [0.71309524 0.59032258 0.54766949 0.59267241 0.6598063 ]
Mean Test Fold AUC: 0.6207132038916885
Std Test Fold AUC: 0.05849439264431433</code></pre>
</div>
</div>
<div id="cell-99" class="cell" data-outputid="bf4ef18b-5b68-4921-f0ae-e750c669aaa9" data-execution_count="149">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>X_without_bodymass_sex <span class="op">=</span> X_df[[<span class="st">'Flipper Length (mm)'</span>, <span class="st">'Species_Chinstrap penguin (Pygoscelis antarctica)'</span>, <span class="st">'Species_Gentoo penguin (Pygoscelis papua)'</span>, <span class="st">'Island_Dream'</span>, <span class="st">'Island_Torgersen'</span>]]</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>test_fold_auc <span class="op">=</span> cross_val_score(log_model, X_without_bodymass_sex, y_df, cv<span class="op">=</span>cross_val, scoring<span class="op">=</span><span class="st">'roc_auc'</span>)</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Test Fold AUC values:'</span>, test_fold_auc)</span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Mean Test Fold AUC:'</span>, test_fold_auc.mean())</span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Std Test Fold AUC:'</span>, test_fold_auc.std())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Test Fold AUC values: [0.72857143 0.66935484 0.58580508 0.6950431  0.71186441]
Mean Test Fold AUC: 0.6781277724509611
Std Test Fold AUC: 0.05013839724785316</code></pre>
</div>
</div>
<div id="cell-100" class="cell" data-outputid="d15752e7-d9fe-443b-aa14-c80bc0444be5" data-execution_count="150">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>X_without_bodymass_species <span class="op">=</span> X_df[[<span class="st">'Flipper Length (mm)'</span>, <span class="st">'Island_Dream'</span>, <span class="st">'Island_Torgersen'</span>, <span class="st">'Sex_MALE'</span>]]</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>test_fold_auc <span class="op">=</span> cross_val_score(log_model, X_without_bodymass_species, y_df, cv<span class="op">=</span>cross_val, scoring<span class="op">=</span><span class="st">'roc_auc'</span>)</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Test Fold AUC values:'</span>, test_fold_auc)</span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Mean Test Fold AUC:'</span>, test_fold_auc.mean())</span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Std Test Fold AUC:'</span>, test_fold_auc.std())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Test Fold AUC values: [0.57619048 0.63387097 0.65783898 0.5700431  0.52905569]
Mean Test Fold AUC: 0.5933998441008348
Std Test Fold AUC: 0.0464159117389316</code></pre>
</div>
</div>
<div id="cell-101" class="cell" data-outputid="0c25bc8b-0453-4523-955e-596953786ff8" data-execution_count="151">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>X_without_bodymass_island <span class="op">=</span> X_df[[<span class="st">'Flipper Length (mm)'</span>, <span class="st">'Species_Chinstrap penguin (Pygoscelis antarctica)'</span>, <span class="st">'Species_Gentoo penguin (Pygoscelis papua)'</span>,  <span class="st">'Sex_MALE'</span>]]</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>test_fold_auc <span class="op">=</span> cross_val_score(log_model, X_without_bodymass_island, y_df, cv<span class="op">=</span>cross_val, scoring<span class="op">=</span><span class="st">'roc_auc'</span>)</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Test Fold AUC values:'</span>, test_fold_auc)</span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Mean Test Fold AUC:'</span>, test_fold_auc.mean())</span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Std Test Fold AUC:'</span>, test_fold_auc.std())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Test Fold AUC values: [0.70238095 0.66774194 0.57944915 0.61314655 0.65496368]
Mean Test Fold AUC: 0.6435364545037486
Std Test Fold AUC: 0.04291827162162581</code></pre>
</div>
</div>
<div id="cell-102" class="cell" data-outputid="f97c7635-770c-462d-ec61-b95b87d7650e" data-execution_count="152">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>X_without_bodymass_sex_flipper <span class="op">=</span> X_df[[ <span class="st">'Species_Chinstrap penguin (Pygoscelis antarctica)'</span>, <span class="st">'Species_Gentoo penguin (Pygoscelis papua)'</span>, <span class="st">'Island_Dream'</span>, <span class="st">'Island_Torgersen'</span>]]</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>test_fold_auc <span class="op">=</span> cross_val_score(log_model, X_without_bodymass_sex_flipper, y_df, cv<span class="op">=</span>cross_val, scoring<span class="op">=</span><span class="st">'roc_auc'</span>)</span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Test Fold AUC values:'</span>, test_fold_auc)</span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Mean Test Fold AUC:'</span>, test_fold_auc.mean())</span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Std Test Fold AUC:'</span>, test_fold_auc.std())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Test Fold AUC values: [0.73095238 0.59677419 0.54449153 0.69181034 0.69612591]
Mean Test Fold AUC: 0.6520308705484796
Std Test Fold AUC: 0.06981890117769665</code></pre>
</div>
</div>
<div id="cell-103" class="cell" data-outputid="4435fc6e-c53f-4269-e021-680da717db54" data-execution_count="153">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>X_without_bodymass_sex_island <span class="op">=</span> X_df[[<span class="st">'Flipper Length (mm)'</span>, <span class="st">'Species_Chinstrap penguin (Pygoscelis antarctica)'</span>, <span class="st">'Species_Gentoo penguin (Pygoscelis papua)'</span>]]</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>test_fold_auc <span class="op">=</span> cross_val_score(log_model, X_without_bodymass_sex_island, y_df, cv<span class="op">=</span>cross_val, scoring<span class="op">=</span><span class="st">'roc_auc'</span>)</span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Test Fold AUC values:'</span>, test_fold_auc)</span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Mean Test Fold AUC:'</span>, test_fold_auc.mean())</span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Std Test Fold AUC:'</span>, test_fold_auc.std())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Test Fold AUC values: [0.70357143 0.67096774 0.57838983 0.69181034 0.68159806]
Mean Test Fold AUC: 0.6652674817593937
Std Test Fold AUC: 0.04476298260022657</code></pre>
</div>
</div>
<div id="cell-104" class="cell" data-outputid="e9b75fde-ddfd-4b4a-e2b4-7eff36b19781" data-execution_count="154">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>X_without_bodymass_sex_species <span class="op">=</span> X_df[[<span class="st">'Flipper Length (mm)'</span>, <span class="st">'Island_Dream'</span>, <span class="st">'Island_Torgersen'</span>]]</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>test_fold_auc <span class="op">=</span> cross_val_score(log_model, X_without_bodymass_sex_species, y_df, cv<span class="op">=</span>cross_val, scoring<span class="op">=</span><span class="st">'roc_auc'</span>)</span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Test Fold AUC values:'</span>, test_fold_auc)</span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Mean Test Fold AUC:'</span>, test_fold_auc.mean())</span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Std Test Fold AUC:'</span>, test_fold_auc.std())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Test Fold AUC values: [0.57142857 0.64677419 0.65995763 0.69396552 0.55932203]
Mean Test Fold AUC: 0.6262895886470574
Std Test Fold AUC: 0.052206458916240865</code></pre>
</div>
</div>
<p>Now that the mean test fold AUC has stopped increasing we can say that the best logistic regression model includes the following variables:</p>
<ul>
<li><code>Flipper Length (mm)</code></li>
<li><code>Species</code></li>
<li><code>Island</code></li>
</ul>
<p>The best model has a Mean Test Fold AUC of 0.6781277724509611 <span class="math inline">\(\pm\)</span> 0.05013839724785316</p>
<div id="cell-106" class="cell" data-outputid="bc20afef-eb30-4941-f02f-050ee247fb43" data-execution_count="155">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>X_best <span class="op">=</span>  X_df[[<span class="st">'Flipper Length (mm)'</span>, <span class="st">'Species_Chinstrap penguin (Pygoscelis antarctica)'</span>, <span class="st">'Species_Gentoo penguin (Pygoscelis papua)'</span>, <span class="st">'Island_Dream'</span>, <span class="st">'Island_Torgersen'</span>]]</span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>test_fold_auc <span class="op">=</span> cross_val_score(log_model, X_best, y_df, cv<span class="op">=</span>cross_val, scoring<span class="op">=</span><span class="st">'roc_auc'</span>)</span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Test Fold AUC values:'</span>, test_fold_auc)</span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Mean Test Fold AUC:'</span>, test_fold_auc.mean())</span>
<span id="cb90-5"><a href="#cb90-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Std Test Fold AUC:'</span>, test_fold_auc.std())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Test Fold AUC values: [0.72857143 0.66935484 0.58580508 0.6950431  0.71186441]
Mean Test Fold AUC: 0.6781277724509611
Std Test Fold AUC: 0.05013839724785316</code></pre>
</div>
</div>
</section>
</section>
<section id="best-model-discussion" class="level2">
<h2 class="anchored" data-anchor-id="best-model-discussion">7. Best Model Discussion</h2>
<p>Here, we merge our best features matrix and target array in order to split the dataset.</p>
<div id="cell-109" class="cell" data-execution_count="156">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>final_df <span class="op">=</span> pd.concat([X_best, y_df], axis<span class="op">=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-110" class="cell" data-outputid="069d145f-9c88-4d6d-ed23-01ca2cb97a0c" data-execution_count="157">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>df_train, df_test<span class="op">=</span>train_test_split(final_df, test_size<span class="op">=</span><span class="fl">0.2</span>, random_state<span class="op">=</span><span class="dv">207</span>)</span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>df_train</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="157">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Flipper Length (mm)</th>
<th data-quarto-table-cell-role="th">Species_Chinstrap penguin (Pygoscelis antarctica)</th>
<th data-quarto-table-cell-role="th">Species_Gentoo penguin (Pygoscelis papua)</th>
<th data-quarto-table-cell-role="th">Island_Dream</th>
<th data-quarto-table-cell-role="th">Island_Torgersen</th>
<th data-quarto-table-cell-role="th">y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1</td>
<td>-1.069474</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">279</td>
<td>2.003117</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">174</td>
<td>-0.712196</td>
<td>1</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">75</td>
<td>-0.354918</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">104</td>
<td>-0.212006</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">83</td>
<td>-0.783651</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">257</td>
<td>1.502928</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">78</td>
<td>-0.712196</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">50</td>
<td>-1.069474</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>-0.426373</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
</tbody>
</table>

<p>266 rows × 6 columns</p>
</div>
</div>
</div>
<p>Then we create the train features matrix and target array in order to fit the model.</p>
<div id="cell-112" class="cell" data-execution_count="158">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>x_train <span class="op">=</span> df_train[[<span class="st">'Flipper Length (mm)'</span>, <span class="st">'Species_Chinstrap penguin (Pygoscelis antarctica)'</span>, <span class="st">'Species_Gentoo penguin (Pygoscelis papua)'</span>, <span class="st">'Island_Dream'</span>, <span class="st">'Island_Torgersen'</span>]]</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>y_train <span class="op">=</span> df_train[<span class="st">'y'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Fitted Model</strong></p>
<div id="cell-114" class="cell" data-outputid="4a952354-1a3a-4233-ed25-9e3d498f7312" data-execution_count="159">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>log_model.fit(x_train, y_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="159">
<style>#sk-container-id-2 {color: black;}#sk-container-id-2 pre{padding: 0;}#sk-container-id-2 div.sk-toggleable {background-color: white;}#sk-container-id-2 label.sk-toggleable__label {cursor: pointer;display: block;width: 100%;margin-bottom: 0;padding: 0.3em;box-sizing: border-box;text-align: center;}#sk-container-id-2 label.sk-toggleable__label-arrow:before {content: "▸";float: left;margin-right: 0.25em;color: #696969;}#sk-container-id-2 label.sk-toggleable__label-arrow:hover:before {color: black;}#sk-container-id-2 div.sk-estimator:hover label.sk-toggleable__label-arrow:before {color: black;}#sk-container-id-2 div.sk-toggleable__content {max-height: 0;max-width: 0;overflow: hidden;text-align: left;background-color: #f0f8ff;}#sk-container-id-2 div.sk-toggleable__content pre {margin: 0.2em;color: black;border-radius: 0.25em;background-color: #f0f8ff;}#sk-container-id-2 input.sk-toggleable__control:checked~div.sk-toggleable__content {max-height: 200px;max-width: 100%;overflow: auto;}#sk-container-id-2 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {content: "▾";}#sk-container-id-2 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-2 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-2 input.sk-hidden--visually {border: 0;clip: rect(1px 1px 1px 1px);clip: rect(1px, 1px, 1px, 1px);height: 1px;margin: -1px;overflow: hidden;padding: 0;position: absolute;width: 1px;}#sk-container-id-2 div.sk-estimator {font-family: monospace;background-color: #f0f8ff;border: 1px dotted black;border-radius: 0.25em;box-sizing: border-box;margin-bottom: 0.5em;}#sk-container-id-2 div.sk-estimator:hover {background-color: #d4ebff;}#sk-container-id-2 div.sk-parallel-item::after {content: "";width: 100%;border-bottom: 1px solid gray;flex-grow: 1;}#sk-container-id-2 div.sk-label:hover label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-2 div.sk-serial::before {content: "";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: 0;}#sk-container-id-2 div.sk-serial {display: flex;flex-direction: column;align-items: center;background-color: white;padding-right: 0.2em;padding-left: 0.2em;position: relative;}#sk-container-id-2 div.sk-item {position: relative;z-index: 1;}#sk-container-id-2 div.sk-parallel {display: flex;align-items: stretch;justify-content: center;background-color: white;position: relative;}#sk-container-id-2 div.sk-item::before, #sk-container-id-2 div.sk-parallel-item::before {content: "";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: -1;}#sk-container-id-2 div.sk-parallel-item {display: flex;flex-direction: column;z-index: 1;position: relative;background-color: white;}#sk-container-id-2 div.sk-parallel-item:first-child::after {align-self: flex-end;width: 50%;}#sk-container-id-2 div.sk-parallel-item:last-child::after {align-self: flex-start;width: 50%;}#sk-container-id-2 div.sk-parallel-item:only-child::after {width: 0;}#sk-container-id-2 div.sk-dashed-wrapped {border: 1px dashed gray;margin: 0 0.4em 0.5em 0.4em;box-sizing: border-box;padding-bottom: 0.4em;background-color: white;}#sk-container-id-2 div.sk-label label {font-family: monospace;font-weight: bold;display: inline-block;line-height: 1.2em;}#sk-container-id-2 div.sk-label-container {text-align: center;}#sk-container-id-2 div.sk-container {/* jupyter's `normalize.less` sets `[hidden] { display: none; }` but bootstrap.min.css set `[hidden] { display: none !important; }` so we also need the `!important` here to be able to override the default hidden behavior on the sphinx rendered scikit-learn.org. See: https://github.com/scikit-learn/scikit-learn/issues/21755 */display: inline-block !important;position: relative;}#sk-container-id-2 div.sk-text-repr-fallback {display: none;}</style><div id="sk-container-id-2" class="sk-top-container"><div class="sk-text-repr-fallback"><pre>LogisticRegression()</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br>On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class="sk-container" hidden=""><div class="sk-item"><div class="sk-estimator sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-2" type="checkbox" checked=""><label for="sk-estimator-id-2" class="sk-toggleable__label sk-toggleable__label-arrow">LogisticRegression</label><div class="sk-toggleable__content"><pre>LogisticRegression()</pre></div></div></div></div></div>
</div>
</div>
<div id="cell-115" class="cell" data-outputid="5ca03179-d030-4d31-a88a-c1ffee26be13" data-execution_count="160">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a>log_model.intercept_</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="160">
<pre><code>array([2.83531012])</code></pre>
</div>
</div>
<div id="cell-116" class="cell" data-outputid="76c132dd-0074-4473-b5dc-c1284b46e8de" data-execution_count="161">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>log_model.coef_</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="161">
<pre><code>array([[ 0.36187172, -0.72803128, -0.4582208 , -0.43334694, -0.75551075]])</code></pre>
</div>
</div>
<p><strong>Equation</strong></p>
<p><span class="math display">\[\begin{align*}
&amp;\quad{Clutch Completion} = \\
&amp;\quad \;\;\;\; 2.83531012 \\
&amp;\quad + 0.36187172\_Flipper\_Length (mm) \\
&amp;\quad - 0.72803128\_Species\_Chinstrap\_penguin (Pygoscelis\_antarctica) \\
&amp;\quad - 0.4582208\_Species\_Gentoo\_penguin (Pygoscelis\_papua) \\
&amp;\quad - 0.43334694\_Island\_Dream \\
&amp;\quad - 0.75551075\_Island\_Torgersen \\
\end{align*}\]</span></p>
<div id="cell-119" class="cell" data-outputid="736447e8-cbb5-413f-9ab6-23bbeb61e409" data-execution_count="162">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>x_train.corr()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="162">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Flipper Length (mm)</th>
<th data-quarto-table-cell-role="th">Species_Chinstrap penguin (Pygoscelis antarctica)</th>
<th data-quarto-table-cell-role="th">Species_Gentoo penguin (Pygoscelis papua)</th>
<th data-quarto-table-cell-role="th">Island_Dream</th>
<th data-quarto-table-cell-role="th">Island_Torgersen</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Flipper Length (mm)</td>
<td>1.000000</td>
<td>-0.195260</td>
<td>0.869489</td>
<td>-0.410813</td>
<td>-0.279304</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Species_Chinstrap penguin (Pygoscelis antarctica)</td>
<td>-0.195260</td>
<td>1.000000</td>
<td>-0.393592</td>
<td>0.691391</td>
<td>-0.215579</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Species_Gentoo penguin (Pygoscelis papua)</td>
<td>0.869489</td>
<td>-0.393592</td>
<td>1.000000</td>
<td>-0.569275</td>
<td>-0.304290</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Island_Dream</td>
<td>-0.410813</td>
<td>0.691391</td>
<td>-0.569275</td>
<td>1.000000</td>
<td>-0.311805</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Island_Torgersen</td>
<td>-0.279304</td>
<td>-0.215579</td>
<td>-0.304290</td>
<td>-0.311805</td>
<td>1.000000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><strong>Multicollinearity</strong></p>
<p>Using a threashold of 0.7, there is one pair of variables with a strong correlation, being Flipper Length and Species(Gentoo penguin) have a correlation coefficient of 0.869. This means that the dataset exhibits an issue with multicollinearity.</p>
<p><strong>Slope Interpretations</strong></p>
<p>Although we have Z-score scaled the numerical variables so that the standard deviations were the same, our dataset’s issue with multicollinearity means we are not able to interpret the magnitudes of the slopes as indicating how important they are to predicting Clutch Completion. They may be misleading.</p>
<p><strong>Overfitting Explanatory Variables</strong></p>
<p>The model with Flipper Length, Species, and Island is determined to be the best performing model. This means that some of the original variables, such as Body Mass and Sex, were likely overfitting the model. This is suggested by that Body Mass and Sex both had a weak association with clutch completion. Body mass and Sex both also had weak associations with the current variables in the models. This means that Body mass and Sex are both irrelevant explanatory variables for our purposes.</p>
<p><strong>Test ROC and AUC</strong></p>
<div id="cell-124" class="cell" data-execution_count="163">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>x_test <span class="op">=</span> df_test[[<span class="st">'Flipper Length (mm)'</span>, <span class="st">'Species_Chinstrap penguin (Pygoscelis antarctica)'</span>, <span class="st">'Species_Gentoo penguin (Pygoscelis papua)'</span>, <span class="st">'Island_Dream'</span>, <span class="st">'Island_Torgersen'</span>]]</span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a>y_test <span class="op">=</span> df_test[<span class="st">'y'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-125" class="cell" data-outputid="6b4def08-afbf-40f5-ff27-1853fbb44ce3" data-execution_count="164">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>df_test[<span class="st">"predictive_prob"</span>]<span class="op">=</span>log_model.predict_proba(x_test)[:,<span class="dv">1</span>]</span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>df_test</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="164">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Flipper Length (mm)</th>
<th data-quarto-table-cell-role="th">Species_Chinstrap penguin (Pygoscelis antarctica)</th>
<th data-quarto-table-cell-role="th">Species_Gentoo penguin (Pygoscelis papua)</th>
<th data-quarto-table-cell-role="th">Island_Dream</th>
<th data-quarto-table-cell-role="th">Island_Torgersen</th>
<th data-quarto-table-cell-role="th">y</th>
<th data-quarto-table-cell-role="th">predictive_prob</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">230</td>
<td>0.645461</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0.931545</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">200</td>
<td>-0.998018</td>
<td>1</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>1</td>
<td>0.787978</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">202</td>
<td>-0.712196</td>
<td>1</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>1</td>
<td>0.804743</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">59</td>
<td>-0.640740</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0.931083</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">171</td>
<td>-0.283462</td>
<td>1</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0.827977</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>-0.712196</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>0.860815</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">140</td>
<td>-0.783651</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>1</td>
<td>0.892677</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>-0.426373</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>0.872751</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">268</td>
<td>1.360017</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0.946305</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">289</td>
<td>1.360017</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0.946305</td>
</tr>
</tbody>
</table>

<p>67 rows × 7 columns</p>
</div>
</div>
</div>
<div id="cell-126" class="cell" data-outputid="91d408db-d1af-4518-8f84-f7620b238399" data-execution_count="165">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>fprs, tprs, thresholds <span class="op">=</span> roc_curve(y_true<span class="op">=</span>y_test, y_score<span class="op">=</span>df_test[<span class="st">'predictive_prob'</span>])</span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a>auc <span class="op">=</span> roc_auc_score(y_true<span class="op">=</span>y_test, y_score<span class="op">=</span>df_test[<span class="st">'predictive_prob'</span>])</span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a>auc</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="165">
<pre><code>0.7285714285714286</code></pre>
</div>
</div>
<div id="cell-127" class="cell" data-execution_count="166">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_roc(fprs, tprs, auc, lw<span class="op">=</span><span class="dv">2</span>):</span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a>    plt.plot(fprs, tprs, color<span class="op">=</span><span class="st">'darkorange'</span>, lw<span class="op">=</span>lw,</span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a>             label<span class="op">=</span><span class="st">'ROC curve (area = '</span><span class="op">+</span><span class="bu">str</span>(<span class="bu">round</span>(auc,<span class="dv">3</span>))<span class="op">+</span><span class="st">')'</span>)</span>
<span id="cb105-4"><a href="#cb105-4" aria-hidden="true" tabindex="-1"></a>    plt.plot([<span class="dv">0</span>, <span class="dv">1</span>], [<span class="dv">0</span>, <span class="dv">1</span>], color<span class="op">=</span><span class="st">'navy'</span>, lw<span class="op">=</span>lw, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb105-5"><a href="#cb105-5" aria-hidden="true" tabindex="-1"></a>    plt.xlabel(<span class="st">'False Positive Rate'</span>)</span>
<span id="cb105-6"><a href="#cb105-6" aria-hidden="true" tabindex="-1"></a>    plt.ylabel(<span class="st">'True Positive Rate'</span>)</span>
<span id="cb105-7"><a href="#cb105-7" aria-hidden="true" tabindex="-1"></a>    plt.title(<span class="st">'ROC Curve'</span>)</span>
<span id="cb105-8"><a href="#cb105-8" aria-hidden="true" tabindex="-1"></a>    plt.legend(loc<span class="op">=</span><span class="st">"lower right"</span>)</span>
<span id="cb105-9"><a href="#cb105-9" aria-hidden="true" tabindex="-1"></a>    plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-128" class="cell" data-outputid="14882bba-ec58-4b6f-ed90-cc17a6a644d1" data-execution_count="167">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a>plot_roc(fprs, tprs, auc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/cell-77-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Test ROC and AUC</strong></p>
<p>Looking at the ROC and AUC curve, the AUC score of 0.729 is fairly close to 1. The logistic model will do a decent job when classifiying the observations in the test dataset.</p>
<div id="cell-130" class="cell" data-execution_count="168">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> fpr_tpr_thresh(y, pred_prob, thresh):</span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a>    yhat <span class="op">=</span> <span class="dv">1</span><span class="op">*</span>(pred_prob <span class="op">&gt;=</span> thresh)</span>
<span id="cb107-3"><a href="#cb107-3" aria-hidden="true" tabindex="-1"></a>    tn, fp, fn, tp <span class="op">=</span> confusion_matrix(y_true<span class="op">=</span>y, y_pred<span class="op">=</span>yhat).ravel()</span>
<span id="cb107-4"><a href="#cb107-4" aria-hidden="true" tabindex="-1"></a>    tpr <span class="op">=</span> tp <span class="op">/</span> (fn <span class="op">+</span> tp)</span>
<span id="cb107-5"><a href="#cb107-5" aria-hidden="true" tabindex="-1"></a>    fpr <span class="op">=</span> fp <span class="op">/</span> (fp <span class="op">+</span> tn)</span>
<span id="cb107-6"><a href="#cb107-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {<span class="st">'threshold'</span>: thresh,</span>
<span id="cb107-7"><a href="#cb107-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'fpr'</span>: fpr,</span>
<span id="cb107-8"><a href="#cb107-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'tpr'</span>: tpr}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-131" class="cell" data-execution_count="169">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> []</span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> thresh <span class="kw">in</span> np.arange(<span class="dv">0</span>,<span class="fl">1.01</span>,<span class="fl">.01</span>):</span>
<span id="cb108-3"><a href="#cb108-3" aria-hidden="true" tabindex="-1"></a>    data.append(fpr_tpr_thresh(y_test, df_test[<span class="st">'predictive_prob'</span>], thresh))</span>
<span id="cb108-4"><a href="#cb108-4" aria-hidden="true" tabindex="-1"></a>df_thresh <span class="op">=</span> pd.DataFrame(data<span class="op">=</span>data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-132" class="cell" data-outputid="28af1663-37d1-4950-c191-cf69840559e0" data-execution_count="170">
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a>df_thresh[df_thresh[<span class="st">'tpr'</span>]<span class="op">&gt;=</span><span class="fl">0.6</span>].nsmallest(<span class="dv">1</span>,<span class="st">'fpr'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="170">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">threshold</th>
<th data-quarto-table-cell-role="th">fpr</th>
<th data-quarto-table-cell-role="th">tpr</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">89</td>
<td>0.89</td>
<td>0.142857</td>
<td>0.666667</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><strong>Best Predictive Probability Threshold</strong></p>
<p>The ROC curve shows that there is a section where the both the FPR is close to zero (about 0.15) and TPR is close to 1 (about 0.7), so there exists some predictive probability threshold that will get us somewhat close to an ideal classification.</p>
<p>For our purposes, we will prioritize a high TPR with a low FPR and select a predictive probability threshold of 0.89.</p>
<p>The test FPR and TPR of the classification that would be created are 0.142857 and 0.666667 respectfully.</p>
<p>This means that when predicting Clutch Completion, about 66.7% of completed clutches were were accurately predicted to be complete and 14.3% of not completed clutches were incorrectly predicted to be complete.</p>
</section>
<section id="additional-analysisinsight" class="level2">
<h2 class="anchored" data-anchor-id="additional-analysisinsight">8. Additional Analysis/Insight</h2>
<section id="kmeans-clustering" class="level3">
<h3 class="anchored" data-anchor-id="kmeans-clustering">KMeans Clustering</h3>
<div id="cell-136" class="cell" data-outputid="502c28bb-f536-4802-d77d-da5e66bc0460" data-execution_count="171">
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a>cluster_df <span class="op">=</span> X_df.copy()</span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a>cluster_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="171">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Body Mass (g)</th>
<th data-quarto-table-cell-role="th">Flipper Length (mm)</th>
<th data-quarto-table-cell-role="th">Species_Chinstrap penguin (Pygoscelis antarctica)</th>
<th data-quarto-table-cell-role="th">Species_Gentoo penguin (Pygoscelis papua)</th>
<th data-quarto-table-cell-role="th">Island_Dream</th>
<th data-quarto-table-cell-role="th">Island_Torgersen</th>
<th data-quarto-table-cell-role="th">Sex_MALE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>-0.568475</td>
<td>-1.426752</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>-0.506286</td>
<td>-1.069474</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>-1.190361</td>
<td>-0.426373</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>-0.941606</td>
<td>-0.569284</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>-0.692852</td>
<td>-0.783651</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">328</td>
<td>0.892957</td>
<td>0.931283</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">329</td>
<td>0.799674</td>
<td>1.002739</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">330</td>
<td>1.919069</td>
<td>1.502928</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">331</td>
<td>1.234995</td>
<td>0.788372</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">332</td>
<td>1.483749</td>
<td>0.859828</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
</tbody>
</table>

<p>333 rows × 7 columns</p>
</div>
</div>
</div>
<p>First we will need to decide on the number of clusters for our KMeans clustering. We are utilizing the Elbow Method to determine the number of optimal clusters by fitting the model with a range of values and plotting the sum of squared distances from each point to its assigned center. As the beginning of the elbow is at 2, we will use 2 as our optimal k.</p>
<div id="cell-138" class="cell" data-outputid="e4707a37-aab6-42fa-d69a-4de811838502" data-execution_count="172">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.cluster <span class="im">import</span> KMeans</span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb111-3"><a href="#cb111-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-4"><a href="#cb111-4" aria-hidden="true" tabindex="-1"></a>inertia <span class="op">=</span> []</span>
<span id="cb111-5"><a href="#cb111-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">10</span>):</span>
<span id="cb111-6"><a href="#cb111-6" aria-hidden="true" tabindex="-1"></a>    kmeans <span class="op">=</span> KMeans(n_clusters<span class="op">=</span>k, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb111-7"><a href="#cb111-7" aria-hidden="true" tabindex="-1"></a>    kmeans.fit(cluster_df)</span>
<span id="cb111-8"><a href="#cb111-8" aria-hidden="true" tabindex="-1"></a>    inertia.append(kmeans.inertia_)</span>
<span id="cb111-9"><a href="#cb111-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-10"><a href="#cb111-10" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb111-11"><a href="#cb111-11" aria-hidden="true" tabindex="-1"></a>plt.plot(<span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">10</span>), inertia, marker<span class="op">=</span><span class="st">'o'</span>)</span>
<span id="cb111-12"><a href="#cb111-12" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Elbow Method For Optimal k'</span>)</span>
<span id="cb111-13"><a href="#cb111-13" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Number of clusters'</span>)</span>
<span id="cb111-14"><a href="#cb111-14" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Inertia'</span>)</span>
<span id="cb111-15"><a href="#cb111-15" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/cell-82-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Now we will fit the KMeans model and analyze the resulting clusters.</p>
<div id="cell-140" class="cell" data-outputid="7931f4a0-6385-4cd4-cee2-9e806b36a887" data-execution_count="173">
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a>k_optimal <span class="op">=</span> <span class="dv">2</span></span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a>kmeans <span class="op">=</span> KMeans(n_clusters<span class="op">=</span>k_optimal, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb112-3"><a href="#cb112-3" aria-hidden="true" tabindex="-1"></a>clusters <span class="op">=</span> kmeans.fit_predict(cluster_df)</span>
<span id="cb112-4"><a href="#cb112-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb112-5"><a href="#cb112-5" aria-hidden="true" tabindex="-1"></a>cluster_df[<span class="st">'Cluster'</span>] <span class="op">=</span> clusters</span>
<span id="cb112-6"><a href="#cb112-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb112-7"><a href="#cb112-7" aria-hidden="true" tabindex="-1"></a>cluster_summary <span class="op">=</span> cluster_df.groupby(<span class="st">'Cluster'</span>).mean()</span>
<span id="cb112-8"><a href="#cb112-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(cluster_summary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Body Mass (g)  Flipper Length (mm)  \
Cluster                                       
0            -0.624650            -0.656245   
1             1.094428             1.149784   

         Species_Chinstrap penguin (Pygoscelis antarctica)  \
Cluster                                                      
0                                                 0.316038   
1                                                 0.008264   

         Species_Gentoo penguin (Pygoscelis papua)  Island_Dream  \
Cluster                                                            
0                                         0.000000      0.575472   
1                                         0.983471      0.008264   

         Island_Torgersen  Sex_MALE  
Cluster                              
0                0.221698  0.495283  
1                0.000000  0.520661  </code></pre>
</div>
</div>
<p>Based on our cluster summary, we can see the following:</p>
<p>Cluster 0:</p>
<ul>
<li>Both Body Mass and Flipper Length features are noticebly lower in cluster 0 compared to cluster 1 indicating these penguins are generally smaller in size.</li>
<li>Cluster 0 contains a higher proportion of Chinstrap Penguins and Adelie Penguins, and no Gentoo Penguins. This means Chinstrap and Adelie penguins are smaller in size.</li>
<li>Majority of Cluster 0 penguins live on Dream Island (57.5) and a significant portion live on Torgersen Island (22.2%)</li>
<li>Approximately 49.5% are male.</li>
</ul>
<p>Cluster 1:</p>
<ul>
<li>The Body Mass and Flipper Length is significantly higher indicating these penguins are larger</li>
<li>Dominated by Gentoo penguins</li>
<li>Almost exclusively Biscoe Island</li>
<li>Slightly more males (52.1%)</li>
</ul>
</section>
<section id="principal-component-analysis" class="level3">
<h3 class="anchored" data-anchor-id="principal-component-analysis">Principal Component Analysis</h3>
<p>Now we will use PCA to reduce the dataset to two principal components and visualize the clusters.</p>
<div id="cell-144" class="cell" data-outputid="d5dce889-9eb8-4c9a-8367-1089959f4af4" data-execution_count="174">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.decomposition <span class="im">import</span> PCA</span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb114-3"><a href="#cb114-3" aria-hidden="true" tabindex="-1"></a>pca <span class="op">=</span> PCA(n_components<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb114-4"><a href="#cb114-4" aria-hidden="true" tabindex="-1"></a>principal_components <span class="op">=</span> pca.fit_transform(cluster_df)</span>
<span id="cb114-5"><a href="#cb114-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb114-6"><a href="#cb114-6" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb114-7"><a href="#cb114-7" aria-hidden="true" tabindex="-1"></a>plt.scatter(principal_components[:, <span class="dv">0</span>], principal_components[:, <span class="dv">1</span>], c<span class="op">=</span>clusters, cmap<span class="op">=</span><span class="st">'viridis'</span>, marker<span class="op">=</span><span class="st">'o'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb114-8"><a href="#cb114-8" aria-hidden="true" tabindex="-1"></a>plt.colorbar(label<span class="op">=</span><span class="st">'Cluster'</span>)</span>
<span id="cb114-9"><a href="#cb114-9" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Principal Component 1'</span>)</span>
<span id="cb114-10"><a href="#cb114-10" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Principal Component 2'</span>)</span>
<span id="cb114-11"><a href="#cb114-11" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Cluster Visualization on PCA-reduced Data'</span>)</span>
<span id="cb114-12"><a href="#cb114-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/cell-84-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Based on our two Principal Components (PC1 and PC2), the two clusters are well-separated along PC1 which likely showing the variations in body size and species amongst the two clusters. PC2 on the other hand is showing variances less related to physical size such as geographical distribution.</p>
<p>Interpretation</p>
<p>Based on the clear separations between the two clusters we can see a strong correlation between the species and physical traits like body mass and flipper length. The clusters also show influence of island location on clustering indicating possible evolutionary adaptations specific to each island.</p>
</section>
<section id="clutch-completion-by-cluster" class="level3">
<h3 class="anchored" data-anchor-id="clutch-completion-by-cluster">Clutch Completion by Cluster</h3>
<p>We are analyzing clutch completion rates within each cluster to see if there are significant differences in reproductive success between the clusters. This will help tell us whether physical traits or locations correlate with higher or lower rates of clutch completion which is necessary to know for someone who is involved in conservation.</p>
<div id="cell-148" class="cell" data-outputid="66e3b265-ef97-42e2-a8e4-3139b270bcf8" data-execution_count="175">
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a>cluster_df[<span class="st">'clutch_completion'</span>] <span class="op">=</span> y_df</span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a>cluster_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="175">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Body Mass (g)</th>
<th data-quarto-table-cell-role="th">Flipper Length (mm)</th>
<th data-quarto-table-cell-role="th">Species_Chinstrap penguin (Pygoscelis antarctica)</th>
<th data-quarto-table-cell-role="th">Species_Gentoo penguin (Pygoscelis papua)</th>
<th data-quarto-table-cell-role="th">Island_Dream</th>
<th data-quarto-table-cell-role="th">Island_Torgersen</th>
<th data-quarto-table-cell-role="th">Sex_MALE</th>
<th data-quarto-table-cell-role="th">Cluster</th>
<th data-quarto-table-cell-role="th">clutch_completion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>-0.568475</td>
<td>-1.426752</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>-0.506286</td>
<td>-1.069474</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>-1.190361</td>
<td>-0.426373</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>-0.941606</td>
<td>-0.569284</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>-0.692852</td>
<td>-0.783651</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">328</td>
<td>0.892957</td>
<td>0.931283</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">329</td>
<td>0.799674</td>
<td>1.002739</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">330</td>
<td>1.919069</td>
<td>1.502928</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">331</td>
<td>1.234995</td>
<td>0.788372</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">332</td>
<td>1.483749</td>
<td>0.859828</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>1</td>
</tr>
</tbody>
</table>

<p>333 rows × 9 columns</p>
</div>
</div>
</div>
<div id="cell-149" class="cell" data-outputid="0252c291-a504-4c9f-8052-2176bea1f610" data-execution_count="176">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a>clutch_completion_rates <span class="op">=</span> cluster_df.groupby(<span class="st">'Cluster'</span>)[<span class="st">'clutch_completion'</span>].mean()</span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(clutch_completion_rates)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cluster
0    0.867925
1    0.942149
Name: clutch_completion, dtype: float64</code></pre>
</div>
</div>
<div id="cell-150" class="cell" data-outputid="f061ba09-2103-49e2-d6bd-303fa1754ff6" data-execution_count="177">
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a>sns.barplot(x<span class="op">=</span>clutch_completion_rates.index, y<span class="op">=</span>clutch_completion_rates.values)</span>
<span id="cb118-2"><a href="#cb118-2" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Clutch Completion Rates by Cluster'</span>)</span>
<span id="cb118-3"><a href="#cb118-3" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Cluster'</span>)</span>
<span id="cb118-4"><a href="#cb118-4" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Average Clutch Completion Rate'</span>)</span>
<span id="cb118-5"><a href="#cb118-5" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/cell-87-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This bar chart shows that both clusters exhibit a high clutch completion rate with Cluster 1 showing a slightly higher rate. Both clusters having a high clutch completion rate suggests that regardless of the physical traits, species composition, and geographical location, the penguins generally have a high success rate in completing their clutches. This is a positive indicator from a reproductive success perspective and means that no specific group of penguins needs extra attention towards conservation.</p>
<p>Understanding these clusters can help in targeting conservation efforts more effectively. This is because they tell us what features belong to what penguin and which type of penguins need more focus, helping fulfill our research motivation</p>
<p>KMeans Clustering and PCA also help fulfill our secondary research goal as the clusters showed the nature of the relationship between the explanatory variables (similar nature variables were clustered together) and it also showed us the nature of the relationship between the explanatory variables and the response variable (we can see that all the explanatory variables contribute to a high clutch completion)</p>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">9. Conclusion</h2>
<p>Our model has Mean Test Fold AUC of 0.6781277724509611 with a STD of 0.05013839724785316 and a Mean AUC of 0.7285714285714286 with our highest TPR being 66.7% with the lowest possible FPR 14.3%. Based on these values, I would recommend our model to be used by the animal biologist/conservationist to be used for further research or conservation purposes. This is because our model has a mean AUC of 0.7-0.8, which is considered acceptable and the model has a reasonable discrimination ability between positive and negative classes. Also, the relatively high TPR (close 70%) and low FPR means our model give a good inital estimate as to the number of penguins that completed clutch. This would help with conservation efforts as it can give a rough estimate as to how many penguins will be born seeing as when there are 2 eggs at least one chick survives.</p>
<p>However, our model does have its shortcomings. We do not know for sure whether our chosen model will yield the highest possible average test AUC as we did not try other feature selection methods while determining our best model such as regularization. In our search for the highest possible test AUC we could have used some forms of unsupervised machine learning such as Neural Networks or Random Forests if we were looking for a more complete analysis.</p>
<p>One shortcoming of our analysis is that our model suffers from multicollinearity so we cannot use the magnitude of the slopes to determine which variables are the most important at predicting clutch completition. Another shortcoming is that in the original dataset, 90% of the datapoints had clutch completion as true whereas 10% had false. The lack of false datapoints means our model will be biased towards the majority class because doing so would yield a high accuracy (90% in this case) even if it fails to accurately predict the minority class.</p>
<p>Based on our current analysis, for the future we can possibly analyze and model the temporal trends in clutch completion rates among penguins, determining if there are specific times or conditions under which clutch completion is more likely. We can possibly do this using Time-Series Analysis Techniques like ARIMA or seasonal decomposition.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>