# remote_theme: pages-themes/hacker@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

# title: [Isabella Iniguez]
# description: [Hello hello!!!]


title: Title here
description: desc here
theme: jekyll-theme-hacker